feature(#6): initial structure
Dsek-LTH/landing-page pull request #13
Opened 2020-02-20 18:32 UTC by FilipLeTran

2020-02-20 18:40 UTC, emilwihlander requested changes
Issue #6 were initially created for html structure to have links to about ("Om sektionen"), for companies ("För företag"), etc. not to address actual lay-out. This pull request is therefore somewhat miss directed. It also isn't mobile-friendly.

2020-02-27 16:49 UTC, FilipLeTran commented
Made the responsive and added basic html structure. Also added CSS for the general layout and responsiveness.

2020-02-28 09:58 UTC, frednordell commented on src/index.html
> +            <img class="logo" src="pictures/D-symbol.svg" alt="D-sek">
alt="D-sek symbol" ?

2020-02-28 09:58 UTC, frednordell commented on src/index.html
> +            </div>
Should we standardize the lorem ipsum? @emilwihlander

2020-02-29 23:58 UTC, emilwihlander approved these changes
Looked at it now, this is a great start!

2020-02-29 23:59 UTC, merged